export const storyActionTypes = {
    RESET_GET_STORIES: 'RESET_GET_STORIES',
    GET_STORIES_SUCCESS: 'GET_STORIES_SUCCESS',
    GET_STORIES_FAILURE: 'GET_STORIES_FAILURE',

    GET_STORY_BY_ID_FAILURE: "GET_STORY_BY_ID_FAILURE",
    GET_STORY_BY_ID_SUCCESS: "GET_STORY_BY_ID_SUCCESS",
};